### ISSUE TITLE
QA login, chat, game

### ISSUE THREAD

**Issue by jnkeniaem** [Gaepo-transcendance-fighters/FRONT-END#113]
고쳐야 할 부분 + 고친 부분은 커멘트 작성!

# 발견된 문제사항 login, chat
## 최초 로그인
- [x] 최초 로그인시 에러 발생.
- [x] localstorage, cookie 비우고 http://10.19.231.71:4000/logout에서 로그아웃하고 http://10.19.231.71:3000/home에 접속하면 app/home/page.tsx안의 `console.log("chat socket connect", authState.chatSocket.connected);` chat socket connect false가 출력된다.
- [x] #211

## 일반
- [x] 중복 접속이 가능하다
- [x] 중복 접속시 채팅방 만들고, 방에서 채팅을 치면, 다른 브라우저에서는 채팅이 보여지지도 않고, 보내기도 안됨
- [x] 새로고침했을때 방 안나가짐

## 로그인
- [x] 이중로그인 인증번호 다르게 쳤을때 에러 뜸(캡쳐사진은 아래 코멘트에)
   - [115-QA-second-auth](https://github.com/Gaepo-transcendance-fighters/FRONT-END/tree/115-QA-second-auth)
- [x] 내프로필에서 이차인증 활성화 버튼 누르면 에러뜬다. (캡처사진 아래 코멘트)
- [x] #218
- [x] #230
- [x] #239

#### "이미 로그인 되어있습니다"
- 내가 접속한 창이 아무것도 없더라도, 백엔드 서버에서는 이미 서버에 접속되어있다고 반영되어잇는 경우가 많음. 소켓이 끊어지면 offline 으로 상태 변경이 바로 되어야하는데 안되고 있음. @wochae 
- [x] 로그인 해둔 창을 끄고, 새로운 창으로 로그인 하면 이미 로그인되어있다고 뜬다.

## 이차로그인
- [x] #215

## 메인화면
- [x] 로그인하고 메인화면 처음 접속했을때 프로필 이미지, 닉네임 안 띄워짐. 백 콘솔에도 에러 뜸(캡쳐사진은 아래 코멘트에)
   - 소켓과 로그인시 데이터를 localstorage가 아닌 context API 에 다 담아놓는다. 
   - https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/136#issue-1889008609
- [x] http://10.19.231.71:4000/logout 에서 로그아웃하고 http://10.19.231.71:3000/home 에서 새로고침하면 로그인 페이지로 안가고 그대로 메인화면에 남아있음
- [x] 나랑 우채님이랑 최초 로그인하고 우채님이 메인화면에서 새로고침했을때 같이 브라우저에 있던 우채님도 나도 로그인페이지로 돌아감

## 나의 프로필 보기
- [x] (jeekim) 내 프로필에서 닉네임 변경했을때, 그 모달에선 정상적으로 변경되는데, 메인화면으로 돌아가면 변경된 닉네임 적용 안됨 > main_enter에서 변경된 닉네임 안보내줌
- [x] (jeekim) 2차인증 활성화 버튼 누르고, 마음 바뀌어서 안하고 싶을수도 있는데 2차인증 모달 외의 부분을 눌러도 모달이 안꺼진다 (캡쳐사진은 아래 코멘트에)
- [x] 이미지 업로드 변경 안됨(캡쳐사진은 아래 코멘트에)
- [x] 닉네임 변경
- [x] 내 프로필 페이지에서 이미지가 안뜬다.
- [x] #167
- [x] 프로필에서 새로고침하면 403 에러가 뜬다
- [x] #178
- [x] #217
---- 이미지 업로드하면 bad request 가 뜬다.
- [x] 2차인증 활성화/비활성화에 따른 y/n 표시가 갱신이 안된다.

### 멤버의 상대방 프로필
- [x] #175
- [x] #174
- [x] 프로필의 이미지가 동기화 되어있지 않다.
- [x] #185
- [x] 우채님 프로필 보는데 방 나가면 내 모달로 대체됨

### 멤버리스트
- [x] mute 하면 당사자는 아무런 알림 안뜨지만 방의 다른 사람들은 뮤트된 걸 알 수 있따. 그리고 일정 시간동안 약 10초 메세지는 안보내진다.
- [x] #132
- [x] #139
   - [관련 사진 및 상황](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/113#issuecomment-1711565419)
- [x] 멤버 프로필에서 게임전적 보기 구현필요
- [x] #234

### 친구리스트
- [x] #177
   - 멤버리스트에서 주전님 add했을때 백에서 `isOnline: 0`옴.
   - 9/10/22:11 여전히 친구리스트의 isOnline 동기화 안됨. 친구리스트 프로필에서는 동기화 잘 되어있음. 새로고침하면 반영되어있음.
- [x] 친구 프로필에서 게임전적 보기 구현필요
- [x] #223

### 블락
> 
> - 친구를 블락했다가 블락해제하면 친구리스트에 안넣기로 정함
> - 어떤 유저를 블락하면 그 유저는 디엠이랑 친구 목록에서만 안보이게
> 내가 주전님을 블락하면 주전님 프로필에 dm 버튼 사라짐, 주전님이 내 프로필 눌렀을땐 dm 버튼 그대로.
> 그 대신, 주전님이 나한테 디엠보내도 나한텐 안뜨게
> - 블락은 하류님이 인메모리 구조 정하시면 그때 테스트해볼수잇음

- [x] 친구 블락
- [x] 멤버 블락
- [x] BLOCK DTO 재설정
- [x] 친구 중복 블락 체크
- [x] 멤버 중복 블락 체크
- [x] block list에 들어가면 거기서 블록당한 유저 프로필 보기가 정상적으로 안된다
- [x] 서버 재시작하고, application 비우고 block하면 block 토글에 아무것도 안나타나지만, 그 후 application 비우고 다시 로딩하고 block하면블락 토글에 있다. 한번에 블락리스트에 안들어간다
- [x] #128

### 친구추가/삭제
- [x] (jeekim) 프론트쪽에서 친구 추가할때 중복 처리해야됨. 안그러면 db 친구목록에 친구가 중복으로 들어가있음.
- [x] (jeekim) 친구추가가 안됨 (캡쳐사진은 아래 코멘트에)
- [x] (jeekim) 친구추가 누르고 다시 멤버리스트에서 주전님 누르면 맨위왼쪽에 add block 메뉴 뜸 (캡쳐사진은 아래 코멘트에)
- [x] (jeekim) silee님 브랜치 병합 후 프로필 이미지가 정상적으로 안뜸 (캡쳐사진은 아래 코멘트에)
- [x] 친구목록에서 유저 delete했는데, 멤버리스트에 그 사람 있고, 그 사람 프로필 클릭하면, add가 아니라 delete가 뜸. 동기화가 안됨 
- [x] 친구추가
- [x] 친구삭제
- [x] 친추 후 친구리스트에서 block하면 친구리스트에 남아있음. 두번 블락하면 친구리스트에서 없어지는데, 그 후 다시 친추 하면 이미 친구라고 친추안됨(캡쳐사진은 아래 코멘트에)

### 친선전
- [x] (jeekim) 친선전 버튼 클릭한번하면 괜찮은데, 두번부턴 상대방에 알림 안뜬다
- [x] (jeekim) 재킴님한테 친선전 게임 초대 눌렀을때, 알림모달엔 시리님이 뜸(캡쳐사진은 아래 코멘트에)

### DM
- [x] #156
   - 주전과 우채가 같은 서버에 있을때 우채님이 dm 눌르면 현재 있는 방으로 잘 리디렉션되었다. 
   - 또 어떤 상황에서는 Already exist 라는 err msg 가 response로 온다. 그리고 리디렉션이 안됨. (로직은 방을 새로만들거나 기존의 dm 방으로 리디렉션 되게 만들어짐)
   - 이게 현재 로그인과 연관되어 유저 정보가 잘 안들어오는 상황과 맞닿아 있는듯하다.
- [x] DM 방 만들면 방장 표시가 뜬다 없어야함.
- [x] dm 방 들어가면 방 멤버 목록에서 나의 이미지가 깨져있음. (아래 코멘트에 사진 첨부)
- [x] #214

### 채팅창  (jujeon)
- [x] #130
- [x] 채팅방 처음 들어가면 loading이 계속 뜬다
- [x] #116 작업완료 jujeon 브랜치 병합됨 (page 개념으로 구조 변경)
- [x] 채팅 시 스크롤 자동 내려가기 안됨.
- [x] 채팅 버그 (1) : 다른 사람이 엔터치면 내가 쓰던 문장이 사라진다
- [x] 채팅 버그 (2) : 서버에서 주는 user 값이 이상하다?
  - 하류님과의 대화가서 채팅치면 haryu 의 이름으로 채팅이 보내진다.
  - 주전 지킴님 들어간 public 방에서 대화하면 주전메세지는 주전화면에 보이는데 지킴 메세지는 지킴화면에서만 보이고 주전화면에서는 없다. (jujeon 작업중)
  - public 방에서 주전님, 지킴님 있을때 주전님이 채팅을 보냈을때, console.log에 보낸 사람 인덱스가 아닌 받는 사람의 인덱스가 옴 (캡쳐사진은 아래 코멘트에)
  - dm 방에서 채팅할때 다른 사람으로 보낸이가 표시됩니다.
- [x] #169
- [x] 방 들어가서 새로고침하면 내 입장에선 잘 나가지는데 상대방한텐 반영이 안됨 (제대로 나가지지 않음)
- [x] (jeekim)주전님이랑 나랑 퍼블릭방에 있는데 주전님이 새로고침하면 내가 나가지는걸로 그려짐. (내가 로그인페이지로 가는게 아니라, 주전님이 나가짐. 멤버리스트엔 주전님, 채팅방리스트에 채팅방 주전's)

### 방설정 (jujeon)
- [x] 비밀번호 변경 안됨.
- [x] 일반 멤버가 비번 업데이트 눌렀을때 알람 안뜸 : 백엔드에서 상태코드를 안보내줬음!

### 채팅방 입장 / 나가기 / 전환 (jujeon)
- [x] 방을 만들고, 접속을 종료하고 다시 접속하면 방이 남아있다.
- [x] public 아무 방에서 대화를 나누고 로비로 나갔다가 같은 방을 들어오면 대화내용이 살아남아있다. 그러나 다른방 갔다오면 사라짐
- [x] 방에 나 혼자 남아있을때, 브라우저창을 닫으면, 다시 접속했을때 방이 남아있다.
- [x] #145
- [x] #222
- [x] #213
- [x] #232

# 게임
- [게임 QA](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/189#issue-1899649200)
## 테스트 해봐야 할 상황
- [x] 게임 중 새로고침
- [ ] 게임 종료 이후 뒤로가기
  지킴>주전 친선전 후 결과페이지 나왔을때,
    지킴 뒤로가기 누르면 option select페이지로 전환됨. 그 페이지에서 메인화면으로 돌아가기 버튼 안되고, 뒤로 가기 버튼 누르면 도망가기로 메인화면으로 나갈 수 있음
    지킴 후 주전이 뒤로가기 버튼 누르면 게임도중화면으로 전환됨. 한번 더 뒤로가기 버튼 누르면 option select 페이지로 전환됨.
  그 후 반대방향으로 다시 친선전 게임 초대했을때 수락 누르면 한 사람은 고구마 페이지, 다른 사람은 메인화면에 그대로
- [x] 게임 중 새로고침
- [x] 게임 중 뒤로가기
### 소켓 이슈
- [x] 게임종료 후 메인화면으로 돌아가면 3초 뒤 login 으로 쫒겨난다. socket 연결이 끊긴 듯하다.
- [x] 로컬스토리지 값이 남아있을때 메인화면에서 새로고침하면 소켓 연결이 안됐는지 바로 로그인 창으로 쫒겨난다. 이때 이미지도 받아와져있다. 브라우저를 켜고 첫 접속을 하고(localstorage, cookie, 4000 logout 세개 다 한 상태) 로그인해서 메인화면 들어가면 3초 지나도 로그인 페이지로 안나가짐. 
* (버그는 아님) fresh한 상태(localstorage, cookie, 4000 logout 세개 다 한 상태)에서 메인화면에서 로컬스토리지 비우고, 쿠키 비우고, 로그아웃 안하면 로그인페이지로 안나가짐.

### 게임 공통
- [x] #201
- [x] (hoslim) 게임 결과 페이지에서 아직 결과를 제대로 받지 못해요ㅠㅠ : 
   - REST API로 결과를 출력해주는 기능 구현 필요.
- [x] (jeekim) 채팅 방에 들어간 상태에서 게임으로 넘어갔다가 돌아오면 방이 없어져있어야하는데 프론트에서는 방이 그려져있다.
- [x] 친선전 결과 페이지까지 나온 후 뒤로가기 버튼 두번 눌렀더니 게임화면으로 돌아가진다 ([코멘트에 사진](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/189#issuecomment-1722454967))
- [x] #199
- [ ] 게임 중간에 도망가고 다시 게임 하려면 게임 서버 터짐
- [x] 애니메이션 부분의 css key 에러
- [x] 게임 optionselect 페이지에서 메인으로 돌아가기 버튼 누르면 로그인페이지로 나가짐
- [ ] 한명은 게임 큐에 들어가잇는 상황에서 한명이 로그인 해서 들어올려고 하니 터져있다. 로그인해서 터졌는지는 확실하지 않음 [참고사진](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/189#issuecomment-1723041867)
#### 게임결과 페이지
[참조 사진](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/113#issuecomment-1723274433)
- [x] 게임 결과페이지에서 win Rate 소수점 1자리에서 절삭해야한다.
- [x] #233
- [x] 한명이 0점으로 끝나면 서버가 터진다.
- [x] 랜덤전일때 게임 중 화면 밑에 맵은 잘 나와있는데, mode랑 rankspeed가 안나온다. (사진 아래)

### 랭크전
- [x] #202
### 친선전
- [x] 새로고침 이후 초대가 안돼요ㅠㅠ
- [x] 초대 후 다시 초대가 안돼요ㅠㅠ : 친선전 요청하고, 상대방이 거절하면, 내 화면에서 친선전 요청 모달창이 사라지지 않음. 아무것도 못함.
- [x] 친선전 상대방도 수락했을때 고구마 페이지까지 왔는데, 게임 화면으로 넘어가지지 않는다
- [ ] 친선전 상대방도 수락했을때 고구마 페이지까지 오고, 뒤로 가기로 메인화면으로 갔는데, 몇초 뒤 로그인 페이지로 가졌다
- [x] #197
- [x] 친선전에서 option select 페이지로 안넘어가짐 #198 
   - dto 맞춰서 해결함
### 게임전적
- [x] #203
   - 서버에서 win lose rankpoint 0 0 0 으로 주고 있었다. 값이 반영이 안된 값을 준다
#### 게임중 상태 관련 로직
- 친선전 모달 혹은 게임시작 버튼을 눌러서 화면이 넘어가면 게임중 상태로 변경하고, 게임중상태일때는 친선전 보내지기를 막아야 한다.
- [x] 상대가 게임 화면에 넘어갔을때 친선전 보내면 안받아진다.
- [x] 상대가 친선전 신청 모달 받았을때 제 3자가 친선전 모달 보낼때 꼬인다. 

기타 등등 qa
- [x] 로컬스토리지에 값이 있는 채로 다시 홈페이지로 들어가서 기능 사용하기
- [x] 기능 사용 중 새로고침
- [x] #205

## ETC
- [x] (jeekim) 주소창에 namespace 입력하면 해당 페이지로 안가고, 메인화면으로 리디렉됨(캡쳐동영상은 아래 코멘트에)

## CSS
- [x] #140
- [x] #143

**Comment by jnkeniaem** [comment]
/home/pingpong/workspace/FRONT-END/frontend/app/mypage/page.tsx
`승률 :{" "}
                            {Math.floor(
                              (userData.Win / (userData.Win + userData.Lose)) *
                                100
                            )}`
                            
<img width="102" alt="Screenshot 2023-08-28 at 2 00 23 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/45ad338f-3874-45b8-bc6b-29b65f8fbfb9">

- [x] 한번도 게임 한적 없으면 승률이 nan으로 뜨는데, 이 경우만 예외로 숫자 0을 띄우게 할거임
- [x] 승"률"이니까 숫자 옆에 '%' 기호 붙이는게 자연스러울 것 같아서 붙일 예정



`userData.Win₩ ₩userData.Lose`

- [x] 서버에선 "w"in, "l"ose로 뜨기 때문에 소문자로 바꿈

**Comment by joonseong11** [comment]
## [버그] 발견된 문제사항 

### 로그인

### 무한스크롤
- [ ] 무한스크롤시 종종 중복된 메세지 요청 및 응답이 온다. 리팩토링 필요

### 채팅방 입장 / 나가기 / 전환

### CSS
- [ ]  Send 버튼 누르면 자동으로 input 으로 포커싱 되는 기능이 mui 에서는 동작하지 않는다 해결필요

**Comment by joonseong11** [comment]
메세지를 입력해도 빈내용 채팅이 쳐진다. 그리고 "jaekim : 엥" 보다 아래에 나와야하는데 위에 메세지가 나온다.

<img width="734" alt="Screenshot 2023-08-28 at 2 33 56 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/f309ff1a-0d6d-4f56-80ba-d5e8b4240f74">

**Comment by jnkeniaem** [comment]
버그는 아니지만
- 방 생성 모달에서 입력창 autofocus
- 방 생성 버튼 누르지 않고 엔터키 눌러도 방 생성 되게 함

**Comment by jnkeniaem** [comment]
재킴님한테 친선전 게임 초대 눌렀을때, 알림모달엔
<img width="601" alt=" " src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/d41ffbd0-ec27-4772-ab25-682e247a58bf">
시리님이 뜸
Silee 님께 친선전 경기를 요청하였습니다. > {prop.nickname} 님께 친선전 경기를 요청하였습니다.

**Comment by jnkeniaem** [comment]
친구추가가 안됨
![image](https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/93f4dbf7-5784-4d96-a603-d723519a571e)

해결 : 
`{showlist
            ? showlist.map((user, idx) => (
                <Friend key={idx} prop={user as IUserProp} />
              ))
            : []}` > `{showlist
            && showlist.map((user, idx) => (
                <Friend key={idx} prop={user as IUserProp} />
              ))}`



`}, [friendState.friendList, friendState.blockList, select]);` > `}, [friendState.friendList, friendState.blockList, select, showlist]);`


`data: JSON.stringify(friendReqData),` > `data: friendReqData`



`friendDispatch({ type: "SET_FRIENDLIST", value: res.data })` > `value: res.data.result`


FriendReqData에 `userIdx : number;` 추가

**Comment by jnkeniaem** [comment]
친구추가 누르고 다시 멤버리스트에서 주전님 누르면 맨위왼쪽에 add block 메뉴 뜸
   <img width="1014" alt="Screenshot 2023-08-30 at 2 35 04 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/59325bc0-e5f2-425b-a925-1e97a3fe7bb9">

해결 : addFriend에 `handleCloseMenu();` 추가

**Comment by jnkeniaem** [comment]
silee님 브랜치 병합 후
       <img width="503" alt="Screenshot 2023-08-30 at 2 07 48 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/ee70838a-57a5-4aee-8ce6-51daa3b872df">
       프로필 이미지가 정상적으로 안뜸
       > 해결 : `imgData` > `imgUrl`로 바꿈

**Comment by jnkeniaem** [comment]
2차인증 활성화 버튼 누르고, 마음 바뀌어서 안하고 싶을수도 있는데 2차인증 모달 외의 부분을 눌러도 모달이 안꺼진다
        <img width="648" alt="Screenshot 2023-08-30 at 3 10 13 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/db9e70aa-a876-4717-9355-0be55bd595ce">
        
해결 : <Modal>이 <Button> 자식이였는데, 둘다 동등한 위치에 있게 변경

**Comment by jnkeniaem** [comment]
public 방에서 주전님, 지킴님 있을때 주전님이 채팅을 보냈을때, console.log에 
  <img width="486" alt="Screenshot 2023-08-28 at 2 53 28 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/4467ea54-e5cf-463c-9de2-669624269e8e">
  보낸 사람 인덱스가 아닌 받는 사람의 인덱스가 옴

**Comment by jnkeniaem** [comment]
2차인증 활성화 버튼 누르고, 마음 바뀌어서 안하고 싶을수도 있는데 2차인증 모달 외의 부분을 눌러도 모달이 안꺼진다 <img alt="Screenshot 2023-08-30 at 3 10 13 PM" width="648" src="https://user-images.githubusercontent.com/80810728/264245398-db9e70aa-a876-4717-9355-0be55bd595ce.png">

**Comment by jnkeniaem** [comment]
주소창에 namespace 입력하면 해당 페이지로 안가고, 메인화면으로 리디렉됨

https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/29c00097-a1dc-4e6e-849a-175409115f64

**Comment by jnkeniaem** [comment]
이미지 업로드 변경 안됨
<img width="303" alt="Screenshot 2023-09-01 at 7 45 26 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/3a4305ae-9342-409a-a024-c6e78aabb225">
<img width="1125" alt="Screenshot 2023-09-01 at 7 45 40 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/97d853bb-7ea4-485f-82a5-a9fd71e1b5fa">

**Comment by jnkeniaem** [comment]
이중로그인 인증번호 다르게 쳤을때 에러 뜸
<img width="1438" alt="Screenshot 2023-09-03 at 4 05 57 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/85a4a8a5-40a2-4c8b-938a-64dd79547a3b">

**Comment by jnkeniaem** [comment]
친구목록에서 유저 delete했는데, 멤버리스트에 그 사람 있고, 그 사람 프로필 클릭하면, add가 아니라 delete가 뜸. 동기화가 안됨

<img width="1067" alt="Screenshot 2023-09-03 at 8 01 13 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/e509f200-23ae-4148-b944-932ee555db5a">

**Comment by jnkeniaem** [comment]
친구프로필이나 멤버프로필에서 dm 버튼 눌렀을때 에러 뜸
<img width="652" alt="Screenshot 2023-09-03 at 8 22 42 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/aef9b56e-98b2-4536-8ad9-aa26fcdb8cfc">
> 우채님이 targetNickname말고 인덱스로 찾는게 좋을것같다고 하심!
해결 : 백 코드 수정(imguri imgurl dto 다른거 일치 등)

**Comment by jnkeniaem** [comment]
로그인하고 메인화면 처음 접속했을때 프로필 이미지, 닉네임 안 띄워짐. 백 콘솔에도 에러 뜸
<img width="494" alt="Screenshot 2023-09-06 at 6 25 17 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/2fe8f1a7-9e67-42d8-b586-59d6246fc9d7">

**Comment by jnkeniaem** [comment]
친추 후 친구리스트에서 block하면 

- [x] 친구리스트에 남아있음. 

- [ ] 두번 블락하면 친구리스트에서 없어지는데, 그 후 다시 친추 하면 이미 친구라고 친추안됨

<img width="264" alt="Screenshot 2023-09-06 at 7 08 12 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/4b784e50-2917-4746-96ea-53149d6d22c1">
`console.log("3")`이 찍혀야하는데 안찍힘

**Comment by joonseong11** [comment]
dm 방 들어가면 방 멤버 목록에서 나의 이미지가 깨져있음.
<img width="331" alt="Screenshot 2023-09-07 at 6 47 22 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/6e18fee5-20d5-49ce-adf1-989454e99978">

**Comment by wochae** [comment]
<img width="1082" alt="image" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/101040879/23327212-246f-488f-be9d-c80341ab4e6b">
이리 내려와봐유

**Comment by wochae** [comment]
<img width="1082" alt="image" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/101040879/887d6c49-7e76-45ad-bb13-0b01383940c7">
주전 방장 방에서 우채 관리자 임명 후 퇴장, 그 뒤에 돌아올 때, 관리자 주전으로 귀환, 해당 주전 우 클릭 시, unset admin 이 안 뜨고,
set admin 드롭다운 아이템이 클릭 되지 않음!

**Comment by wochae** [comment]
<img width="966" alt="image" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/101040879/8ef754ac-21c2-476c-9e72-0178b07b02c5">

2023/09/10 21:46 dev 에서 발생한 에러입니다!
로그인하고 생성된 주전님의 방에 입장하려고 할 때 발생합니다.

**Comment by joonseong11** [comment]
<img width="881" alt="Screenshot 2023-09-11 at 1 44 48 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/65519af8-7aa7-4382-98e0-22bd8f93bfcb">

상대가 닉네임 바꾼뒤 내가 블락해제 하면 터진다

**Comment by joonseong11** [comment]
<img width="916" alt="Screenshot 2023-09-12 at 5 15 45 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/ac97771a-0f4b-45b7-8510-33558b3cb5ff">

**Comment by joonseong11** [comment]
![Screenshot 2023-09-18 at 6 52 19 PM](https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/f59e92e0-a731-42cb-aa35-d252dbaf6480)

**Comment by joonseong11** [comment]
<img width="1237" alt="Screenshot 2023-09-18 at 9 55 43 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/14862c99-923a-465c-85ca-384e985cd266">

**Comment by jnkeniaem** [comment]
랜덤전일때 게임 중 화면 밑에 맵은 잘 나와있는데, mode랑 rankspeed가 안나온다.
<img width="519" alt="Screenshot 2023-09-20 at 3 46 43 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/02a3d649-bee8-44fa-a8c1-10973910f831">

**Comment by joonseong11** [comment]
![Screenshot 2023-09-20 at 4 41 42 PM](https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/33fd06c7-23b5-4890-9cc2-2bea1de6ba0b)

**Comment by jnkeniaem** [comment]
unset admin이 안뜨는 상황
A가 방장인 상태, B,C를 모두 admin으로 등록하고 방을 나감
2. A가 방을 나가서 B가 새로운 방장이 되었는데, B가 C를 보았을 때, unsetadmin이 나오지 않고, 같은 admin이라 kick,ban,mute 할 수 없다고 나옴.
+) 다시 방에 들어온 A는 set admin, mute, kick, ban 모두 됨.
