### ISSUE TITLE
GAME QA 

### ISSUE THREAD

**Issue by HiHoi** [Gaepo-transcendance-fighters/FRONT-END#189]
# 게임 qa 입니다!
## 테스트 해봐야 할 상황
- [ ] 게임 중 새로고침
- [ ] 게임 종료 이후 뒤로가기
- [ ] 게임 중 새로고침
- [ ] 게임 중 뒤로가기
### 소켓 이슈
- [ ] 게임종료 후 메인화면으로 돌아가면 3초 뒤 login 으로 쫒겨난다. socket 연결이 끊긴 듯하다.
- [ ] 로컬스토리지 값이 남아있을때 메인화면에서 새로고침하면 소켓 연결이 안됐는지 바로 로그인 창으로 쫒겨난다. 이때 이미지도 받아와져있다. 브라우저를 켜고 첫 접속을 하고(localstorage, cookie, 4000 logout 세개 다 한 상태) 로그인해서 메인화면 들어가면 3초 지나도 로그인 페이지로 안나가짐. 
* (버그는 아님) fresh한 상태(localstorage, cookie, 4000 logout 세개 다 한 상태)에서 메인화면에서 로컬스토리지 비우고, 쿠키 비우고, 로그아웃 안하면 로그인페이지로 안나가짐.

### 게임 공통
- [x] #201
- [x] (hoslim) 게임 결과 페이지에서 아직 결과를 제대로 받지 못해요ㅠㅠ : 
   - REST API로 결과를 출력해주는 기능 구현 필요.
- [ ] (jeekim) 채팅 방에 들어간 상태에서 게임으로 넘어갔다가 돌아오면 방이 없어져있어야하는데 프론트에서는 방이 그려져있다.
- [x] 친선전 결과 페이지까지 나온 후 뒤로가기 버튼 두번 눌렀더니 게임화면으로 돌아가진다 ([코멘트에 사진](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/189#issuecomment-1722454967))
- [x] #199
- [ ] 게임 optionselect 페이지에서 메인으로 돌아가기 버튼 누르면 로그인페이지로 나가짐
- [ ] 한명은 게임 큐에 들어가잇는 상황에서 한명이 로그인 해서 들어올려고 하니 터져있다. 로그인해서 터졌는지는 확실하지 않음 [참고사진](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/189#issuecomment-1723041867)
### 랭크전
- [x] #202
- [ ] 랭크전 들어왔는데 혼자 게임 혼자 시작되버리고 터져버림 [참고사진](https://github.com/Gaepo-transcendance-fighters/FRONT-END/issues/189#issuecomment-1723036393)
### 친선전
- [ ] 새로고침 이후 초대가 안돼요ㅠㅠ
- [x] 초대 후 다시 초대가 안돼요ㅠㅠ : 친선전 요청하고, 상대방이 거절하면, 내 화면에서 친선전 요청 모달창이 사라지지 않음. 아무것도 못함.
- [ ] 친선전 상대방도 수락했을때 고구마 페이지까지 왔는데, 게임 화면으로 넘어가지지 않는다
- [ ] 친선전 상대방도 수락했을때 고구마 페이지까지 오고, 뒤로 가기로 메인화면으로 갔는데, 몇초 뒤 로그인 페이지로 가졌다
- [x] #197
- [x] 친선전에서 option select 페이지로 안넘어가짐 #198 
   - dto 맞춰서 해결함   
- [ ] 상대 로그아웃 했는데 친선전 보내면 상대는 갇힌다
### 게임전적
- [x] #203
   - 서버에서 win lose rankpoint 0 0 0 으로 주고 있었다. 값이 반영이 안된 값을 준다

기타 등등 qa
- [x] 로컬스토리지에 값이 있는 채로 다시 홈페이지로 들어가서 기능 사용하기
- [x] 기능 사용 중 새로고침
- [x] #205
- [ ] 채팅방에 들어가면, 채팅방에 들어온 사람들의 프로필 이미지를 계속 요청해서 받는다. 메모리가 계속 쌓인다!

**Comment by jnkeniaem** [comment]
친선전 상대방도 수락했을때 고구마 페이지까지 왔는데, 게임 화면으로 넘어가지지 않는다

**Comment by jnkeniaem** [comment]
친선전 상대방도 수락했을때 고구마 페이지까지 오고, 뒤로 가기로 메인화면으로 갔는데, 몇초 뒤 로그인 페이지로 가졌다

**Comment by jnkeniaem** [comment]
!dm 방에서 우채님이랑 친선전 고구마 페이지 까지 갔다가 뒤로가기 눌러서 메인 화면으로 왔을때 메인화면에 그 채팅방 남아있었다

**Comment by joonseong11** [comment]
<img width="906" alt="Screenshot 2023-09-17 at 7 29 28 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/e210a1fd-8cf8-4ad3-868c-c532441530dc">

**Comment by jnkeniaem** [comment]
친선전 결과 페이지까지 나온 후 뒤로가기 버튼 두번 눌렀더니

<img width="1440" alt="Screenshot 2023-09-17 at 8 21 49 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/80810728/a96e318d-71d7-4355-a847-52d967ec9b10">
게임 화면으로 들어가진다

**Comment by jnkeniaem** [comment]
친선전에서 option select 페이지로 안넘어가졌는데 dto 맞춰서 해결함

**Comment by joonseong11** [comment]
<img width="1150" alt="Screenshot 2023-09-18 at 6 17 19 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/741085fe-2ce1-46e2-a5d4-068f1a0e6d07">

랭크전 들어왔는데 혼자 게임 혼자 시작되버리고 터져버림

**Comment by joonseong11** [comment]
<img width="1041" alt="Screenshot 2023-09-18 at 6 21 07 PM" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/87654307/8af5eef0-c18e-44d2-b159-7fb9b27cb004">
한명은 게임 큐에 들어가잇는 상황에서 한명이 로그인 해서 들어올려고 하니 터져있다. 로그인해서 터졌는지는 확실하지 않음
